#!/bin/bash

plugin_filename="${0##*/}"
username="${plugin_filename#*_}"
#Хабр понимает только логины с подчёркиваниями вместо -
username="${username//-/_}"

if [ "$1" = "config" ]; then
    echo "graph_title KarmaGraph $username
graph_category web 
graph_vlabel #
karma.label Karma
rating.label Rating"
    exit
fi

exec 33<>/dev/tcp/habrahabr.ru/80
echo -e "GET /api/profile/$username/ HTTP/1.0\r\nHost: habrahabr.ru\r\n" >&33
read -t 5 -d $'\0' REPLY <&33

for v in karma rating; do
    if [[ $REPLY =~ "<$v>"(.*)"</$v>" ]]; then
	echo "$v.value ${BASH_REMATCH[1]}"
    else
	echo "$v.value U"
    fi
done
