#!/bin/bash

plugin_filename="${0##*/}"
username="${plugin_filename#*_}"
#Хабр понимает только логины с подчёркиваниями вместо -
username="${username//-/_}"

if [ "$1" = "config" ]; then
    echo "graph_title KarmaGraph $username
graph_category web 
graph_vlabel #
karma.label Karma
rating.label Rating"
    exit
fi

REPLY=$(curl -sLm 10 "https://habrahabr.ru/api/profile/$username/")

for v in karma rating; do
    [[ $REPLY =~ "<$v>"(.*)"</$v>" ]]
    echo "$v.value ${BASH_REMATCH[1]:-U}"
done
